// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzcw2Ts_AoBaqWukPKQxPriza3Dexhcbg',
    appId: '1:130671191292:web:4dedaaa6a1c367744ba379',
    messagingSenderId: '130671191292',
    projectId: 'connectycubevideocall',
    authDomain: 'connectycubevideocall.firebaseapp.com',
    storageBucket: 'connectycubevideocall.appspot.com',
    measurementId: 'G-FHPHE2G7VV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD59k2Vh3nVTxnuRLMZW-AUHPmjN9Yr1uA',
    appId: '1:130671191292:android:52bb65faf37241024ba379',
    messagingSenderId: '130671191292',
    projectId: 'connectycubevideocall',
    storageBucket: 'connectycubevideocall.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCF92QjQTaDqzw4iVhvSmNEEc9aJSiRa-0',
    appId: '1:130671191292:ios:03706795dbbaa44b4ba379',
    messagingSenderId: '130671191292',
    projectId: 'connectycubevideocall',
    storageBucket: 'connectycubevideocall.appspot.com',
    iosBundleId: 'uz.technounitgroup.vmeeting',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCF92QjQTaDqzw4iVhvSmNEEc9aJSiRa-0',
    appId: '1:130671191292:ios:608d88189b2e4fd64ba379',
    messagingSenderId: '130671191292',
    projectId: 'connectycubevideocall',
    storageBucket: 'connectycubevideocall.appspot.com',
    iosBundleId: 'uz.technounitgroup.vmeeting.RunnerTests',
  );
}
